services:
  mariadb:
    image: mariadb:10.8
    container_name: MariDb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ImdbOpenDB
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./MariaDBData:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: ..
      dockerfile: template.Dockerfile
    container_name: TestSpring
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3306/ImdbOpenDB
      SPRING_DATASOURCE_USERNAME: ${MARIADB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MARIADB_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
