name: ProductionCI  # Name of the GitHub Actions workflow

# Enable Buildkit to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

# Define the events that trigger this workflow
on:
  # Trigger on push to the main branch after a pull request is merged
  push:
    branches: ['main']
    paths-ignore: ['docs/**']

# Define concurrency settings to ensure multiple workflows don't interfere
concurrency:
  group: ${{ github.head_ref || github.run_id }}  # Group by head ref or run ID
  cancel-in-progress: true  # Cancel previous runs if a new one is triggered

# Define jobs to run in this workflow
jobs:
  # Job for building and deploying the application
  build_and_deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu version as the runner
    environment: production  # Specify that this runs on the production environment

    steps:
      - name: Checkout Code Repository  # Step to checkout the code repository
        uses: actions/checkout@v4  # Use GitHub's checkout action (v4)

      - name: Build the Docker stack  # Step to build the Docker stack
        env:  # Set environment variables from GitHub Secrets
          MARIADB_ROOT_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}  # Production secrets
          MARIADB_USER: ${{ secrets.MARIADB_USER }}

        run: |
          docker compose -f Docker/docker-compose.yml build  # Build all services defined in Docker/docker-compose.yml

      - name: Log in to Docker Hub  # Step to log in to Docker Hub
        run: |
          echo "dckr_pat_2YFGPju7TdRPMdeXk7dP-4T9UvE" | docker login -u "blackwolfben" --password-stdin

      - name: Push Docker images to Docker Hub  # Step to push the images
        run: |
          docker compose -f Docker/docker-compose.yml push  # Push all images defined in Docker/docker-compose.yml

      - name: Deploy Application with Docker  # Step to deploy the application
        run: |
          echo "Deploying the application with Docker..."
          docker compose -f Docker/docker-compose.yml up -d --remove-orphans  # Start the stack in detached mode
          echo "Application deployed successfully."

      - name: Tear down the previous Docker stack
        run: |
          docker compose -f Docker/docker-compose.yml down  # Take down the stack
          echo "Previous Docker stack taken down."
